
CREATE DATABASE bookmarks_db;
USE bookmarks_db;
CREATE TABLE Bookmark (
    id MEDIUMINT NOT NULL AUTO_INCREMENT, 
    URL VARCHAR(255) NOT NULL, 
    title VARCHAR(255) NOT NULL, 
    dateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);